version: "3"
services:

#  postgres:
#    container_name: postgres-axon
#    image: "postgres:12"
#    environment:
#      POSTGRES_USER: "postgres"
#      POSTGRES_PASSWORD: "PNvHnvLzxH"
#      POSTGRES_DB: eventstoredb
#      PGDATA: "/data/postgres"
#    volumes:
#      - postgres-data:/var/lib/postgresql/data
#      - /var/lib/postgres
#    ports:
#      - "5432:5432"
#    restart: unless-stopped

#  redis:
#    image: "redis:alpine"
#    ports:
#      - "6379:6379"

  mongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    volumes:
      - "mongodb_data_container:/data/db"

volumes:
  mongodb_data_container:
  postgres-data:
